### PR TITLE
don't use vars, use our

### PR DESCRIPTION
**Pull request by haarg**

### CODE REVIEW

**Comment by polloparatodos** [comment]
@haarg do you want to release this to the cpan? If you do, please bump the version:

https://metacpan.org/pod/Class::Data::Inheritable

**Comment by haarg** [comment]
I would be willing to, but I don't have the needed permissions: https://metacpan.org/dist/Class-Data-Inheritable/permissions

**Comment by polloparatodos** [comment]
You're right - I didn't even think about the permissions. @schwern would have to adjust permissions that since they have owner to the module. I am merely a co-maintainer. I'll push an update with this change on your behalf.

**Comment by polloparatodos** [comment]
Hey @haarg - Sorry for the delay, I've submitted this, and I'll let you know once it's live as v0.10

Update: It's live [here](https://metacpan.org/release/RSHERER/Class-Data-Inheritable-0.10/view/lib/Class/Data/Inheritable.pm)

**Comment by haarg** [comment]
Thanks!

**Pull request merged**
